version: '3'

networks:
    jarch-infra-global-network-proxy-admin:
      external: true
    network-app:

volumes:
  volume-jira-db-data:
    driver: local
  volume-jira-ui-data:
    driver: local

services:
 
  db:
    image: mysql:5.5
    networks:
      - network-app
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_DATABASE=jira
    volumes:
      - volume-jira-db-data:/var/lib/mysql
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.jra.swarm-node-type == infra-persistence]
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
      labels:
        - "jra.environment-flip=blue"
        - "jra.application-name=jarch-infra-admin-jira-db"
        - "jra.container-name=jarch-infra-admin-jira-db"

  ui:
    image: cptactionhank/atlassian-jira:7.5.2
    ports:
      - 8193:8080
    networks:
      - jarch-infra-global-network-proxy-admin
      - network-app
    volumes:
      - volume-jira-ui-data:/var/atlassian/jira
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.jra.swarm-node-type == admin-ui-web]
      labels:
        - "traefik.docker.network=jarch-infra-global-network-proxy-admin"
        - "traefik.port=8080"
        - "traefik.frontend.rule=Host:${ENV_DOMAIN_PREFIX}jira.joericearchitect.com"
        - "jra.environment-flip=blue"
        - "jra.application-name=jarch-infra-admin-jira-ui"
        - "jra.container-name=jarch-infra-admin-jira-ui"
        - "jra.domain-name=${ENV_DOMAIN_PREFIX}jira.joericearchitect.com"
