version: '3'

#####################################################################
# Set up the Docker Apps / Services. 
#
# Global proxies are defined outside of stacks and distribute traffic 
# across multiple stacks.
#
# The global proxies use external overlay networks.  These networks 
# will also be defined outside of stacks and used across multiple stacks
# The external overlays are expected to already be created before this
# stack is deployed.
#####################################################################

networks:
  jarch-infra-global-network-proxy-admin:
    external: true

volumes:
  volume-docker-registry-data:
    driver: local
  volume-docker-registry-certs:
    driver: local
  volume-portainer-data:
    driver: local

services:

  registry:
    image: registry:2.5.2
    ports:
      - 8183:5000
    networks:
      - jarch-infra-global-network-proxy-admin
    volumes:
      - volume-docker-registry-data:/var/lib/registry
      - volume-docker-registry-certs:/certs
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.jra.swarm-node-type == infra-repos]
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
      labels:
        - "traefik.docker.network=jarch-infra-global-network-proxy-admin"
        - "traefik.port=5000"
        - "traefik.frontend.rule=Host:${ENV_DOMAIN_PREFIX}docker.joericearchitect.com"
        - "jra.environment-flip=blue"
        - "jra.application-name=jarch-infra-docker-registry"
        - "jra.container-name=jarch-infra-docker-registry"
        - "jra.domain-name=${ENV_DOMAIN_PREFIX}docker.joericearchitect.com"


  ui-portainer:
    image: portainer/portainer:1.15.1
    ports:
      - 8184:9000
    networks:
      - jarch-infra-global-network-proxy-admin
    command:
      -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - volume-portainer-data:/data
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
      labels:
        - "traefik.docker.network=jarch-infra-global-network-proxy-admin"
        - "traefik.port=9000"
        - "traefik.frontend.rule=Host:${ENV_DOMAIN_PREFIX}dockerui.joericearchitect.com"
        - "jra.environment-flip=blue"
        - "jra.application-name=jarch-infra-docker-ui-portainer"
        - "jra.container-name=jarch-infra-docker-ui-portainer"
        - "jra.domain-name=${ENV_DOMAIN_PREFIX}dockerui.joericearchitect.com"

  ui-visualizer:
    image: dockersamples/visualizer
    ports:
      - 8190:8080
    networks:
      - jarch-infra-global-network-proxy-admin
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
      labels:
        - "traefik.docker.network=jarch-infra-global-network-proxy-admin"
        - "traefik.port=8080"
        - "traefik.frontend.rule=Host:${ENV_DOMAIN_PREFIX}dockervisual.joericearchitect.com"
        - "jra.environment-flip=blue"
        - "jra.application-name=jarch-infra-docker-ui-visualizer"
        - "jra.container-name=jarch-infra-docker-ui-visualizer"
        - "jra.domain-name=${ENV_DOMAIN_PREFIX}dockervisual.joericearchitect.com"
        